# Generated by Django 4.1.4 on 2023-01-14 20:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='act',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=10)),
                ('full_sch', models.CharField(max_length=150, null=True)),
                ('active_term', models.CharField(default='0', max_length=30)),
                ('school', models.CharField(default='0', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='class_fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(default='', max_length=15, null=True)),
                ('classes', models.CharField(default=0, max_length=15, null=True)),
                ('fee', models.FloatField(default=0, max_length=15, null=True)),
                ('datey', models.CharField(default=datetime.date(2023, 1, 14), max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='classn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_id', models.CharField(default=0, max_length=30, null=True)),
                ('number', models.CharField(default=0, max_length=30, null=True)),
                ('classA', models.CharField(default=0, max_length=30, null=True)),
                ('classB', models.CharField(default=0, max_length=30, null=True)),
                ('classC', models.CharField(default=0, max_length=30, null=True)),
                ('classD', models.CharField(default=0, max_length=30, null=True)),
                ('classE', models.CharField(default=0, max_length=30, null=True)),
                ('classF', models.CharField(default=0, max_length=30, null=True)),
                ('classG', models.CharField(default=0, max_length=30, null=True)),
                ('classH', models.CharField(default=0, max_length=30, null=True)),
                ('classI', models.CharField(default=0, max_length=30, null=True)),
                ('classJ', models.CharField(default=0, max_length=30, null=True)),
                ('classK', models.CharField(default=0, max_length=30, null=True)),
                ('classL', models.CharField(default=0, max_length=30, null=True)),
                ('classM', models.CharField(default=0, max_length=30, null=True)),
                ('classN', models.CharField(default=0, max_length=30, null=True)),
                ('classO', models.CharField(default=0, max_length=30, null=True)),
                ('school', models.CharField(default=0, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='sch_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=10)),
                ('school', models.CharField(max_length=150, null=True)),
                ('date', models.DateField(default=datetime.date(2023, 1, 14))),
                ('full_sch', models.CharField(default='0', max_length=30)),
                ('contact_details', models.CharField(default='0', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='use',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=10)),
                ('school', models.CharField(max_length=150, null=True)),
                ('date', models.DateField(default=datetime.date(2023, 1, 14))),
                ('full_sch', models.CharField(default='0', max_length=30)),
                ('contact_details', models.CharField(default='0', max_length=10)),
            ],
        ),
    ]
