# Generated by Django 4.1.4 on 2023-01-14 20:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fees_update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_id', models.CharField(default='', max_length=10)),
                ('firstname', models.CharField(max_length=150, null=True)),
                ('middlename', models.CharField(max_length=100, null=True)),
                ('lastname', models.CharField(max_length=100, null=True)),
                ('level', models.CharField(max_length=10, null=True)),
                ('amount', models.FloatField(default=0, max_length=12, null=True)),
                ('amountpaid_term1', models.FloatField(default=0, max_length=12, null=True)),
                ('amountpaid_term2', models.FloatField(default=0, max_length=12, null=True)),
                ('amountpaid_term3', models.FloatField(default=0, max_length=12, null=True)),
                ('fee', models.FloatField(default=0, max_length=12, null=True)),
                ('balance', models.FloatField(default=0, max_length=12, null=True)),
                ('school', models.CharField(default='', max_length=12, null=True)),
                ('datey', models.DateField(default=datetime.date(2023, 1, 14), max_length=40, null=True)),
                ('school_full', models.CharField(default='', max_length=30, null=True)),
                ('mother_name', models.CharField(default='None', max_length=30, null=True)),
                ('mother_contact', models.CharField(default='None', max_length=30, null=True)),
                ('father_name', models.CharField(default='None', max_length=30, null=True)),
                ('father_contact', models.CharField(default='None', max_length=30, null=True)),
                ('promote', models.CharField(default=1, max_length=30, null=True)),
            ],
        ),
    ]
