# Generated by Django 4.1.4 on 2023-01-20 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploading', '0002_remove_fees_update_datebirth'),
    ]

    operations = [
        migrations.AddField(
            model_name='fees_update',
            name='datebirth',
            field=models.CharField(default=0, max_length=30, null=True),
        ),
    ]
